version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - app-network

  mongo_1:
    image: mongo:4
    command: mongod --replSet appReplicaSet
    volumes:
      - './db-data/1:/data/db'
      - ${PWD}/mongo/rs_config.js:/docker-entrypoint-initdb.d/rs_config.js
    networks:
      - app-network
    extra_hosts:
      - "mongo_1:127.0.0.1"
    restart: on-failure

  mongo_2:
    image: mongo:4
    command: mongod --replSet appReplicaSet
    volumes:
      - './db-data/2:/data/db'
    networks:
      - app-network
    restart: on-failure

  mongo_3:
    image: mongo:4
    command: mongod --replSet appReplicaSet
    volumes:
      - './db-data/3:/data/db'
    networks:
      - app-network
    restart: on-failure

  front:
    build: ./front
    ports:
      - 8080:80
    networks:
      - app-network

  back:
    build: ./back
    ports:
      - 8082:80
    networks:
      - app-network
    restart: on-failure

  sockets:
    build: ./sockets
    ports:
      - 8083:80
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge
